# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 564882bfa6c003ff32a00de1bf8e4396313052e8f0ddefa7423949ad157d62da892949b0d93574811ea0d491bce4a73943c417c028ea86f2a0b567eb08799f54

test:
  secret_key_base: 47360bf63d41522425eb3680af1e5dec614a786f49e0ee0055c6e47aab544f23eff74d8d9cdb87f192196edd74730ee004bdffe4dd8bf439c24169afe2635d03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
